GIMBAL_ANGLE = 0.0              # TODO
TILESETS_HTTP_SERVER_URL = 0.0  # TODO
OUTPUTS_ROS_HRZ = 0.0           # TODO
RESOLUTION_WIDTH = 1280
RESOLUTION_HEIGHT = 720
CAMERA_FOV = 0.0                # TODO