laser_params:
  publish_rate_hz: 50
  topic_name: "/omni/rangefinder_pub"
  min_range: 0.2
  max_range: 180.0
  frame_id: "range_sensor_frame"

vehicle_params:
  turn_radius_m: 11.5
  vehicle_speed_kmh: 35.0
